---
name: CI
'on':
        #pull_request:
  push:
    branches:
      - master


jobs:
  test:
    name: Molecule test
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    distro: [centos7, centos8]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install molecule[docker] yamllint ansible-lint

      - name: Run molecule test.
        run: molecule test
